VeterinariaEdiMvc2021.Web/Controllers/TipoDeDocumentosController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using VeterinariaEdiMvc.Servicios.Servicios;
using VeterinariaEdiMvc.Servicios.Servicios.Facades;
using VeterinariaEdiMvc2021.Entidades.DTOs.TipoDeDocumento;
using VeterinariaEdiMvc2021.Entidades.ViewModels.TipoDeDocumento;
using VeterinariaEdiMvc2021.Entidades.ViewModels.TipoDeTarea;

namespace VeterinariaEdiMvc2021.Web.Controllers
{
    public class TipoDeDocumentosController : Controller
    {
        private readonly IServiciosTipoDeDocumento _servicio;
        private readonly IMapper _mapper;

        public TipoDeDocumentosController(IServiciosTipoDeDocumento servicio)
        {
            _servicio = servicio;
            _mapper = Mapeador.Mapeador.CrearMapper();
        }

        // GET: TipoDeDocumentos
        public ActionResult Index(int? page=null)
        {
            page = (page ?? 1);
            var listaDto = _servicio.GetLista();
            var listaVm = _mapper.Map<List<TipoDeDocumentoListViewModel>>(listaDto)
                .OrderBy(c => c.Descripcion)
                .ToPagedList((int)page, 5);
            return View(listaVm);
        }

        [HttpGet]

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TipoDeDocumentoEditViewModel tipoDocVm)
        {
            if (!ModelState.IsValid)
            {
                return View(tipoDocVm);
            }

            TipoDeDocumentoEditDto tipoDocDto = _mapper.Map<TipoDeDocumentoEditDto>(tipoDocVm);

            if (_servicio.Existe(tipoDocDto))
            {
                ModelState.AddModelError(string.Empty, "Registro Existente...");
                return View(tipoDocVm);
            }
            try
            {
                _servicio.Guardar(tipoDocDto);
                TempData["Msg"] = "Registro Agregado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(tipoDocVm);

            }
        }

        [HttpGet]

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoDeDocumentoEditDto tipoDocDto = _servicio.GetipoDeDocumentoPorId(id);
            if (tipoDocDto == null)
            {
                return HttpNotFound("Còdigo de Tipo de Documento inexistente...");
            }
            TipoDeDocumentoEditViewModel tipoDocVm = _mapper.Map<TipoDeDocumentoEditViewModel>(tipoDocDto);
            return View(tipoDocVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Delete(TipoDeDocumentoEditViewModel tipoDocVm)
        {
            TipoDeDocumentoEditDto tipoDocDto = _mapper.Map<TipoDeDocumentoEditDto>(tipoDocVm);
            if (_servicio.EstaRelacionado(tipoDocDto))
            {
                ModelState.AddModelError(string.Empty, "Registro relacionado con otra tabla...Baja denegada");
                return View(tipoDocVm);
            }
            try
            {
                tipoDocVm = _mapper.Map<TipoDeDocumentoEditViewModel>(_servicio.GetipoDeDocumentoPorId(tipoDocVm.TipoDeDocumentoId));
                _servicio.Borrar(tipoDocVm.TipoDeDocumentoId);
                TempData["Msg"] = "Registro Borrado...";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {

                ModelState.AddModelError(string.Empty, e.Message);
                return View(tipoDocVm);
            }
        }

        [HttpGet]

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoDeDocumentoEditDto tipoDocDto = _servicio.GetipoDeDocumentoPorId(id);
            TipoDeDocumentoEditViewModel tipoDocVm = _mapper.Map<TipoDeDocumentoEditViewModel>(tipoDocDto);
            return View(tipoDocVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(TipoDeDocumentoEditViewModel tipoDocVm)
        {
            if (!ModelState.IsValid)
            {
                return View(tipoDocVm);
            }
            TipoDeDocumentoEditDto tipoDocDto = _mapper.Map<TipoDeDocumentoEditDto>(tipoDocVm);
            if (_servicio.Existe(tipoDocDto))
            {
                ModelState.AddModelError(string.Empty, "Registro duplicado....");
                return View(tipoDocVm);
            }
            try
            {
                _servicio.Guardar(tipoDocDto);
                TempData["Msg"] = "Registro Modeificado...";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(tipoDocVm);

            }
        }
    }
}

VeterinariaEdiMvc2021.Web/Views/TipoDeDocumentos/Create.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.TipoDeDocumento.TipoDeDocumentoEditViewModel

@{ ViewBag.Title = "Create"; }
<div>
    <h2>Ingrese nuevo Tipo de Documento</h2>

</div>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Nuevo</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success"})

                </div>
            </div>
        </div>
    }

</body>
</html>

VeterinariaEdiMvc2021.Web/Views/TipoDeDocumentos/Delete.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.TipoDeDocumento.TipoDeDocumentoEditViewModel

@{ ViewBag.Title = "Delete"; }
<div>
    <h2>Borre un Tipo de Documento</h2>

</div>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Borrar</title>
</head>
<body>
    <h3>Està seguro de borrar el registro seleccionado?</h3>
    <div>
        <h4>Tipo De Documento</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>

            <dt>
                @Html.DisplayNameFor(model => model.Descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descripcion)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.TipoDeDocumentoId);
            @Html.ValidationSummary(true, "", new { @class = "text-Danger" });
            <div class="form-actions no-color">
                <input type="submit" value="Borrar" class="btn btn-danger" /> |
                @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" });
            </div>
        }
    </div>
</body>
</html>

VeterinariaEdiMvc2021.Web/Views/TipoDeDocumentos/Edit.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.TipoDeDocumento.TipoDeDocumentoEditViewModel

@{ ViewBag.Title = "Edit"; }
<div>
    <h2>Edite un Tipo de Documento</h2>

</div>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tipo De Documento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TipoDeDocumentoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-warning" />
                @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
    }

</body>
</html>

VeterinariaEdiMvc2021.Web/Views/TipoDeDocumentos/Index.cshtml
@model PagedList.IPagedList<VeterinariaEdiMvc2021.Entidades.ViewModels.TipoDeDocumento.TipoDeDocumentoListViewModel>
@using PagedList.Mvc
@{ ViewBag.Title = "Index"; }
<div>
    <a href="@Url.Action("Create","TipoDeDocumentos")" class="btn btn-primary" style="float: right">Nuevo</a>
    <h2>Lista de Tipos de Documentos</h2>

</div>
<hr />
@if (TempData["Msg"] != null)
{
    var msg = TempData["Msg"].ToString();
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Éxito!</strong> @msg
    </div>}
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Descripcion)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.TipoDeDocumentoId }, new { @class = "btn btn-warning" })
                @Html.ActionLink("Borrar", "Delete", new { id = item.TipoDeDocumentoId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
</body>
</html>
Pàgina:  @Model.PageNumber  de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page
}))