VeterinariaEdiMvc2021.Web/Controllers/ProvinciasController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using VeterinariaEdiMvc.Servicios.Servicios;
using VeterinariaEdiMvc.Servicios.Servicios.Facades;
using VeterinariaEdiMvc2021.Entidades.DTOs.Provincia;
using VeterinariaEdiMvc2021.Entidades.ViewModels.Provincia;

namespace VeterinariaEdiMvc2021.Web.Controllers
{
    public class ProvinciasController : Controller
    {
        private readonly IServiciosProvincia _servicio;
        private readonly IServiciosLocalidad _servicioLocalidad;
        private readonly IMapper _mapper;

        public ProvinciasController(IServiciosProvincia servicio, IServiciosLocalidad servicioLocalildad)
        {
            _servicio = servicio;
            _servicioLocalidad = servicioLocalildad;
            _mapper = Mapeador.Mapeador.CrearMapper();
        }

        // GET: Provincias
        public ActionResult Index(int? page=null)
        {
            page = (page ?? 1);
            var listaDto = _servicio.GetListaProvinciaConCantidad();
            var listaVm = _mapper.Map<List<ProvinciaCantidadListViewModel>>(listaDto)
                .OrderBy(c => c.NombreProvincia)
                .ToPagedList((int)page, 5);
            return View(listaVm);
        }


        [HttpGet]

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProvinciaEditViewModel provinciaVm)
        {
            if (!ModelState.IsValid)
            {
                return View(provinciaVm);
            }

            ProvinciaEditDto provinciaDto = _mapper.Map<ProvinciaEditDto>(provinciaVm);

            if (_servicio.Existe(provinciaDto))
            {
                ModelState.AddModelError(string.Empty, "Registro Existente...");
                return View(provinciaVm);
            }
            try
            {
                _servicio.Guardar(provinciaDto);
                TempData["Msg"] = "Registro Agregado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(provinciaVm);

            }
        }

        [HttpGet]

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProvinciaEditDto provinciaDto = _servicio.GetProvinciaPorId(id);
            if (provinciaDto == null)
            {
                return HttpNotFound("Còdigo de Provincia inexistente...");
            }
            ProvinciaEditViewModel provinciaVm = _mapper.Map<ProvinciaEditViewModel>(provinciaDto);
            return View(provinciaVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Delete(ProvinciaEditViewModel provinciaVm)
        {
            ProvinciaEditDto provinciaDto = _mapper.Map<ProvinciaEditDto>(provinciaVm);
            if (_servicio.EstaRelacionado(provinciaDto))
            {
                ModelState.AddModelError(string.Empty, "Registro relacionado con otra tabla...Baja denegada");
                return View(provinciaVm);
            }
            try
            {
                provinciaVm = _mapper.Map<ProvinciaEditViewModel>(_servicio.GetProvinciaPorId(provinciaVm.ProvinciaId));
                _servicio.Borrar(provinciaVm.ProvinciaId);
                TempData["Msg"] = "Registro Borrado...";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {

                ModelState.AddModelError(string.Empty, e.Message);
                return View(provinciaVm);
            }
        }

        [HttpGet]

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProvinciaEditDto provinciaDto = _servicio.GetProvinciaPorId(id);
            ProvinciaEditViewModel provinciaVm = _mapper.Map<ProvinciaEditViewModel>(provinciaDto);
            return View(provinciaVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(ProvinciaEditViewModel provinciaVm)
        {
            if (!ModelState.IsValid)
            {
                return View(provinciaVm);
            }
            ProvinciaEditDto provinciaDto = _mapper.Map<ProvinciaEditDto>(provinciaVm);
            if (_servicio.Existe(provinciaDto))
            {
                ModelState.AddModelError(string.Empty, "Registro duplicado....");
                return View(provinciaVm);
            }
            try
            {
                _servicio.Guardar(provinciaDto);
                TempData["Msg"] = "Registro Modeificado...";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(provinciaVm);

            }
        }
    }
}

VeterinariaEdiMvc2021.Web/Views/Provincias/Create.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.Provincia.ProvinciaEditViewModel

@{ ViewBag.Title = "Create"; }
<div>
    <h2>Ingrese nueva Provincia</h2>

</div>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Nueva</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.NombreProvincia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NombreProvincia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NombreProvincia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                    @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success"})

                </div>
            </div>
        </div>
    }

</body>
</html>

VeterinariaEdiMvc2021.Web/Views/Provincias/Delete.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.Provincia.ProvinciaEditViewModel

@{ ViewBag.Title = "Delete"; }
<div>
    <h2>Borre una Provincia</h2>

</div>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Borrar</title>
</head>
<body>
    <h3>Està seguro de borrar el registro seleccionado?</h3>
    <div>
        <h4>Provincia</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>

            <dt>
                @Html.DisplayNameFor(model => model.NombreProvincia)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NombreProvincia)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.ProvinciaId);
            @Html.ValidationSummary(true, "", new { @class = "text-Danger" });
            <div class="form-actions no-color">
                <input type="submit" value="Borrar" class="btn btn-danger" /> |
                @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" });
            </div>
        }
    </div>
</body>
</html>

VeterinariaEdiMvc2021.Web/Views/Provincias/Details.cshtml
@model PagedList.IPagedList<VeterinariaEdiMvc2021.Entidades.ViewModels.Provincia.ProvinciaDetailsViewModel>
@using PagedList.Mvc
@{
    ViewBag.Title = "Details";
}
<h2>Detalles</h2>
<div>
    <h4>Provincia</h4>
    <hr />
    <dl class="dl-Horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.First().NombreProvincia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.First().NombreProvincia)
        </dd>
    </dl>
    @Html.Partial("_ListaLocalidades", Model.First().Localidades)
    <p>
        @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" })
    </p>

    @*<table class="Table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Localidades[0].NombreLocalidad)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Localidades[0].Provincia)
                </th>
            </tr>
            @foreach (var item in Model.Localidades)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelitem => item.NombreLocalidad)
                </td>

                <td>
                    @Html.DisplayFor(modelitem => item.Provincia)
                </td>

                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.LocalidadId }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Detalles", "Details", new { id = item.LocalidadId }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Borrar", "Delete", new { id = item.LocalidadId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
            }
        </table>*@
</div>
@*<p>
    @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" })*@
@*</p>*@
Pàgina: (@Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber), de: @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page
}))

VeterinariaEdiMvc2021.Web/Views/Provincias/Edit.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.Provincia.ProvinciaEditViewModel

@{ ViewBag.Title = "Edit"; }
<div>
    <h2>Edite una Provincia</h2>

</div>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Provincia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProvinciaId)

        <div class="form-group">
            @Html.LabelFor(model => model.NombreProvincia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreProvincia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreProvincia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-warning" />
                @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
    }

</body>
</html>

VeterinariaEdiMvc2021.Web/Views/Provincias/Index.cshtml
@model PagedList.IPagedList<VeterinariaEdiMvc2021.Entidades.ViewModels.Provincia.ProvinciaCantidadListViewModel>
@using PagedList.Mvc
@{ ViewBag.Title = "Index"; }
<div>
    <a href="@Url.Action("Create","Provincias")" class="btn btn-primary" style="float: right">Nuevo</a>
    <h2>Lista de Provincias</h2>

</div>
<hr />
@if (TempData["Msg"] != null)
{
    var msg = TempData["Msg"].ToString();
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Éxito!</strong> @msg
    </div>}
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().NombreProvincia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().CantidadProvincias)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreProvincia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadProvincias)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.ProvinciaId }, new { @class = "btn btn-warning" })
                @Html.ActionLink("Borrar", "Delete", new { id = item.ProvinciaId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }




</table>
</>
</>
Pàgina:  @Model.PageNumber  de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page
}))