VeterinariaEdiMvc2021.Web/Controllers/ProveedoresController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VeterinariaEdiMvc.Servicios.Servicios.Facades;
using VeterinariaEdiMvc2021.Entidades.DTOs.Proveedor;
using VeterinariaEdiMvc2021.Entidades.Entidades;
using VeterinariaEdiMvc2021.Entidades.ViewModels.Localidad;
using VeterinariaEdiMvc2021.Entidades.ViewModels.Proveedor;
using VeterinariaEdiMvc2021.Entidades.ViewModels.Provincia;

namespace VeterinariaEdiMvc2021.Web.Controllers
{
    public class ProveedoresController : Controller
    {
        private readonly IServiciosProveedor _servicio;
        private readonly IServiciosLocalidad _serviciosLocalidad;
        private readonly IServiciosProvincia _serviciosProvincia;
        private readonly IMapper _mapper;

        public ProveedoresController(IServiciosProveedor servicio, IServiciosLocalidad serviciosLocalidad, IServiciosProvincia serviciosProvincia)
        {
            _servicio = servicio;
            _serviciosLocalidad = serviciosLocalidad;
            _serviciosProvincia = serviciosProvincia;
            _mapper = Mapeador.Mapeador.CrearMapper();
        }


        // GET: Empleados
        public ActionResult Index(int? localidadSeleccionadaId=null, int? page=null)
        {
            page = (page ?? 1);
            //var listaDto = _servicio.GetLista(null);
            //var listaVm = _mapper.Map<List<ProveedorListViewModel>>(listaDto)
            //    .OrderBy(c => c.RazonSocial)
            //    .ThenBy(c => c.Localidad)
            //    .ToPagedList((int)page, 5);
            //return View(listaVm);

            List<Proveedor> lista;

            if (localidadSeleccionadaId != null)
            {
                lista = _servicio.GetLista(localidadSeleccionadaId.Value);

            }
            else
            {
                lista = _servicio.GetLista();
            }

            if (localidadSeleccionadaId != null)
            {
                Session["localidadSeleccionadaId"] = localidadSeleccionadaId;
            }
            else
            {
                if (Session["localidadSeleccionadaId"] != null)
                {
                    localidadSeleccionadaId = (int)Session["localidadSeleccionadaId"];
                }
            }

            if (localidadSeleccionadaId != null)
            {
                if (localidadSeleccionadaId.Value > 0)
                {
                    lista = _servicio.GetLista(localidadSeleccionadaId.Value);
                }
                else
                {
                    lista = _servicio.GetLista();
                }
            }
            else
            {
                lista = _servicio.GetLista();
            }

            //var localidades = provinciaSeleccionadaId.HasValue ? db.Localidades.Where(l => l.ProvinciaId == provinciaSeleccionadaId) : db.Localidades;
            var listaDto = _servicio.GetLista(null);
            var listaVm = _mapper.Map<List<ProveedorListViewModel>>(listaDto)

            .OrderBy(c => c.RazonSocial)
            .ThenBy(c => c.Localidad)
            .ToPagedList((int)page, 5);
            var listaVma = Mapeador.Mapeador.ConstruirListaProveedorListVm(lista);
            var listaLocalidades = _serviciosLocalidad.GetLista();
            listaLocalidades.Insert(0, new Localidad() { LocalidadId = 0, NombreLocalidad = "[Seleccione una Localidad]" });
            listaLocalidades.Insert(1, new Localidad() { LocalidadId = -1, NombreLocalidad = "[Ver Todas]" });
            ViewBag.ListaLocalidades = new SelectList(listaLocalidades, "LocalidadId", "NombreLocalidad", localidadSeleccionadaId);
            return View(listaVma.ToPagedList((int)page, 5));
        }

        [HttpGet]

        public ActionResult Create()
        {
            ProveedorEditViewModel proveedorVm = new ProveedorEditViewModel
            {
                Localidad = _mapper.Map<List<LocalidadListViewModel>>(_serviciosLocalidad.GetLista(null)),
                Provincia = _mapper.Map<List<ProvinciaListViewModel>>(_serviciosProvincia.GetLista())
            };
            return View(proveedorVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProveedorEditViewModel proveedorEditVm)
        {
            if (!ModelState.IsValid)
            {
                proveedorEditVm.Localidad = _mapper.Map<List<LocalidadListViewModel>>(_serviciosLocalidad.GetLista(null));
                proveedorEditVm.Provincia = _mapper.Map<List<ProvinciaListViewModel>>(_serviciosProvincia.GetLista());
                return View(proveedorEditVm);
            }
            ProveedorEditDto proveedorDto = _mapper.Map<ProveedorEditDto>(proveedorEditVm);
            if (_servicio.Existe(proveedorDto))
            {
                ModelState.AddModelError(string.Empty, "Proveedor Existente");
                proveedorEditVm.Localidad = _mapper.Map<List<LocalidadListViewModel>>(_serviciosLocalidad.GetLista(null));
                proveedorEditVm.Provincia = _mapper.Map<List<ProvinciaListViewModel>>(_serviciosProvincia.GetLista());
                return View(proveedorEditVm);

            }
            try
            {
                _servicio.Guardar(proveedorDto);
                TempData["Msg"] = "Proveedor Agregado....";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                proveedorEditVm.Localidad = _mapper.Map<List<LocalidadListViewModel>>(_serviciosLocalidad.GetLista(null));
                proveedorEditVm.Provincia = _mapper.Map<List<ProvinciaListViewModel>>(_serviciosProvincia.GetLista());
                return View(proveedorEditVm);

            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProveedorEditDto proveedorDto = _servicio.GetProveedorPorId(id);
            if (proveedorDto == null)
            {
                return HttpNotFound("Còdigo de Proveedor No Encontrado");
            }
            ProveedorEditViewModel proveedorVm = _mapper.Map<ProveedorEditViewModel>(proveedorDto);
            proveedorVm.Localidad = _mapper.Map<List<LocalidadListViewModel>>(_serviciosLocalidad.GetLista(null));
            proveedorVm.Provincia = _mapper.Map<List<ProvinciaListViewModel>>(_serviciosProvincia.GetLista());
            return View(proveedorVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProveedorEditViewModel proveedorVm)
        {
            if (!ModelState.IsValid)
            {
                proveedorVm.Localidad = _mapper.Map<List<LocalidadListViewModel>>(_serviciosLocalidad.GetLista(null));
                proveedorVm.Provincia = _mapper.Map<List<ProvinciaListViewModel>>(_serviciosProvincia.GetLista());
                return View(proveedorVm);
            }
            ProveedorEditDto proveedorDto = _mapper.Map<ProveedorEditDto>(proveedorVm);
            if (_servicio.Existe(proveedorDto))
            {
                ModelState.AddModelError(string.Empty, "Proveedor Existente");
                proveedorVm.Localidad = _mapper.Map<List<LocalidadListViewModel>>(_serviciosLocalidad.GetLista(null));
                proveedorVm.Provincia = _mapper.Map<List<ProvinciaListViewModel>>(_serviciosProvincia.GetLista());
                return View(proveedorVm);

            }
            try
            {
                _servicio.Guardar(proveedorDto);
                TempData["Msg"] = "Proveedor Editado....";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                proveedorVm.Localidad = _mapper.Map<List<LocalidadListViewModel>>(_serviciosLocalidad.GetLista(null));
                proveedorVm.Provincia = _mapper.Map<List<ProvinciaListViewModel>>(_serviciosProvincia.GetLista());
                return View(proveedorVm);
            }
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var proveedorDto = _servicio.GetProveedorPorId(id);
            if (proveedorDto == null)
            {
                return HttpNotFound("Còdigo de Proveedor inexistente");
            }
            ProveedorListViewModel proveedorVm = _mapper.Map<ProveedorListViewModel>(proveedorDto);
            proveedorVm.Localidad = (_serviciosLocalidad.GetLocalidadPorId(proveedorDto.LocalidadId)).NombreLocalidad;
            return View(proveedorVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ProveedorListViewModel proveedorVm)
        {
            try
            {
                ProveedorListDto proveedorDto = _mapper.Map<ProveedorListDto>(_servicio.GetProveedorPorId(proveedorVm.ProveedorId));
                proveedorVm = _mapper.Map<ProveedorListViewModel>(proveedorDto);
                _servicio.Borrar(proveedorVm.ProveedorId);
                TempData["Msg"] = "Registro borrado...";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(proveedorVm);
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProveedorEditDto proveedorDto = _servicio.GetProveedorPorId(id);
            if (proveedorDto == null)
            {

VeterinariaEdiMvc2021.Web/Views/Proveedores/Create.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.Proveedor.ProveedorEditViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Proveedor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CUIT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CUIT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CUIT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonaDeContacto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonaDeContacto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonaDeContacto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ProvinciaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProvinciaId, new SelectList(Model.Provincia, "ProvinciaId", "NombreProvincia"), "Seleccione Provincia", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProvinciaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalidadId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocalidadId, new SelectList(Model.Localidad, "LocalidadId", "NombreLocalidad"), "Seleccione Localidad", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocalidadId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoFijo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoFijo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoFijo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoMovil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoMovil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoMovil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

@section scripts
{
    <script>
        $(document).ready(function() {
            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
            });

            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
                $("#LocalidadId").append('<option value="0">[Seleccionar Localidad]</option>');

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetLocalidades")',
                    dataType: 'json',
                    data: {
                        provinciaId: $("#ProvinciaId").val()

                    },
                    success: function(localidades) {
                        $.each(localidades,
                            function(i, localidad) {
                                $("#LocalidadId").append('<option value="' + localidad.LocalidadId + '">' + localidad.NombreLocalidad + '</option>');
                            });
                    },
                    error: function(ex) {
                        alert('Error al intentar cargar las localidades.' + ex);
                    }
                });
                return false;
            });
        });

    </script>
}

VeterinariaEdiMvc2021.Web/Views/Proveedores/Delete.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.Proveedor.ProveedorListViewModel

@{ ViewBag.Title = "Delete"; }
<div>
    <h2>Borre un Proveedor</h2>

</div>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Està seguro de borrar este registro?</h3>
    <div>
        <h4>Proveedor</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.CUIT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CUIT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RazonSocial)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RazonSocial)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Direccion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TelefonoMovil)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TelefonoMovil)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Localidad)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Localidad)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.ProveedorId)
            @Html.ValidationSummary(true, "", new { @class = "text-Danger" });

            <div class="form-actions no-color">
                <input type="submit" value="Borrar" class="btn btn-danger" /> |
                @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" });
            </div>
        }
        </div>
</body>
</html>

VeterinariaEdiMvc2021.Web/Views/Proveedores/Details.cshtml
@model VeterinariaEdiMvc2021.Entidades.ViewModels.Proveedor.ProveedorEditViewModel

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h4>Detalle de Empleado</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <body>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.CUIT, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.CUIT, new { htmlAttributes = new { @class = "readonly" } })
                            @Html.ValidationMessageFor(model => model.CUIT, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "readonly" } })
                            @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PersonaDeContacto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.PersonaDeContacto, new { htmlAttributes = new { @class = "readonly" } })
                            @Html.ValidationMessageFor(model => model.PersonaDeContacto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.Direccion, new { htmlAttributes = new { @class = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LocalidadId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.LocalidadId, new SelectList(Model.Localidad, "LocalidadId", "NombreLocalidad"), new { disabled = "disabled" })
                            @Html.ValidationMessageFor(model => model.LocalidadId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProvinciaId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.ProvinciaId, new SelectList(Model.Provincia, "ProvinciaId", "NombreProvincia"), new { disabled = "disabled" })
                            @Html.ValidationMessageFor(model => model.ProvinciaId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TelefonoFijo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.TelefonoFijo, new { htmlAttributes = new { @class = "readonly" } })
                            @Html.ValidationMessageFor(model => model.TelefonoFijo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TelefonoMovil, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.TelefonoMovil, new { htmlAttributes = new { @class = "readonly" } })
                            @Html.ValidationMessageFor(model => model.TelefonoMovil, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "readonly" } })
                            @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.ActionLink("Volver", "Index", "", new { @class = "btn btn-success" })

                        </div>
                    </div>

                </div>
            }

        </body>
    </div>
}

VeterinariaEdiMvc2021.Web/Views/Proveedores/Index.cshtml
@model PagedList.IPagedList<VeterinariaEdiMvc2021.Entidades.ViewModels.Proveedor.ProveedorListViewModel>
@using PagedList.Mvc
@{ ViewBag.Title = "Index"; }
<div>
    <a href="@Url.Action("Create","Proveedores")" class="btn btn-primary" style="float: right">Nuevo</a>
    <h2>Lista de Proveedores</h2>

</div>

@using (Html.BeginForm(null, null, FormMethod.Get, new { @class = "form-inline" }))
{
    <label>Filtar por:</label>
    @Html.DropDownList("localidadSeleccionadaId", ViewBag.ListaLocalidades as SelectList, htmlAttributes: new { @class = "form-control" })
    <input type="submit" class="btn btn-success" value="Filtrar" />
}


@if (TempData["Msg"] != null)
{
    var msg = TempData["Msg"].ToString();
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Éxito!</strong> @msg
    </div>}

<hr />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().CUIT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().RazonSocial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TelefonoMovil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Localidad)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CUIT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RazonSocial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelefonoMovil)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Localidad)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.ProveedorId }, new { @class = "btn btn-warning" })
                @Html.ActionLink("Detalles", "Details", new { id = item.ProveedorId }, new { @class = "btn btn-info" })
                @Html.ActionLink("borrar", "Delete", new { id = item.ProveedorId }, new { @class = "btn btn-danger" })

            </td>
        </tr>
    }

</table>
Pàgina:  @Model.PageNumber  de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page
}))